### ISSUE TITLE
Allow setting a different listening address and port

### ISSUE THREAD

**Issue by juliushaertl** [icewind1991/notify_push#3]
I've been setting this up in my dev env and encountered that it might be good if one could specify a different listening address than 127.0.0.1:80 as when running the notify_push server in an isolated environment like a container where the reverse proxy is handled by a different container.

**Comment by icewind1991** [comment]
You can configure the port it listens on using the `PORT` environment variable

**Comment by juliushaertl** [comment]
Hm, maybe I miss something but even with exposing the port as in https://github.com/icewind1991/notify_push/blob/main/Dockerfile#L19 it would not be reachable then from outside of a container.

**Comment by icewind1991** [comment]
Set it to listen to `0.0.0.0` docker setup should now work
